<?php
$jieqiBlocks['1'] = array (
  'bid' => 0,
  'blockname' => '精品完本',
  'module' => 'article',
  'filename' => 'block_commend',
  'classname' => 'BlockArticleCommend',
  'side' => -1,
  'title' => '精品完本',
  'vars' => '192|193|194',
  'template' => 'block_sort_toplist.html',
  'contenttype' => 1,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 2,
  'showtype' => 0,
);
$jieqiBlocks['2'] = array (
  'bid' => 0,
  'blockname' => '最新完本',
  'module' => 'article',
  'filename' => 'block_commend',
  'classname' => 'BlockArticleCommend',
  'side' => -1,
  'title' => '最新完本',
  'vars' => '199|201|204',
  'template' => 'block_sort_toplist2.html',
  'contenttype' => 1,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 2,
  'showtype' => 0,
);
$jieqiBlocks['3'] = array (
  'bid' => 0,
  'blockname' => '热门完本',
  'module' => 'article',
  'filename' => 'block_commend',
  'classname' => 'BlockArticleCommend',
  'side' => -1,
  'title' => '热门完本',
  'vars' => '202|203|194',
  'template' => 'block_sort_toplist2.html',
  'contenttype' => 1,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 2,
  'showtype' => 0,
);

