<?php
$jieqiAction['system'] = array (
  'register' => 
  array (
    'acttitle' => '会员注册',
    'minscore' => '0',
    'islog' => '0',
    'isvip' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => '1',
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '10',
    'earncredit' => '0',
    'lenmin' => '3',
    'lenmax' => '30',
    'passmin' => 6,
    'needemail' => 0,
    'isreview' => '',
  ),
  'login' => 
  array (
    'acttitle' => '会员登录',
    'minscore' => '0',
    'islog' => '0',
    'isvip' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => '1',
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '2',
    'earncredit' => '0',
    'descscore' => '一天内只有第一次登录获取积分',
    'isreview' => '',
    'lenmin' => '',
    'lenmax' => '',
  ),
  'adclick' => 
  array (
    'acttitle' => '点击广告',
    'minscore' => '0',
    'islog' => '0',
    'isvip' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => '1',
    'paymin' => '0',
    'paymax' => '5',
    'earnscore' => '0',
    'earncredit' => '0',
    'descscore' => '一天内最多计分 5 次',
    'isreview' => '',
    'lenmin' => '',
    'lenmax' => '',
  ),
  'newmessage' => 
  array (
    'acttitle' => '发站内短信',
    'minscore' => '0',
    'islog' => '0',
    'isvip' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => '1',
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '0',
    'earncredit' => '0',
    'isreview' => '',
    'lenmin' => '',
    'lenmax' => '',
  ),
  'ptopic' => 
  array (
    'acttitle' => '会客室发帖',
    'minscore' => '0',
    'islog' => '0',
    'isvip' => '0',
    'ispay' => '0',
    'paytitle' => '',
    'paybase' => '1',
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '0',
    'earncredit' => '0',
    'isreview' => '',
    'lenmin' => '',
    'lenmax' => '',
  ),
  'tip' => 
  array (
    'acttitle' => '打赏会员',
    'minscore' => '0',
    'islog' => '1',
    'isvip' => '1',
    'ispay' => '1',
    'paytitle' => '小说币',
    'paybase' => '1',
    'paymin' => '20',
    'paymax' => '0',
    'earnscore' => '0',
    'earncredit' => '0',
    'ismessage' => 1,
    'isreview' => '',
    'lenmin' => '',
    'lenmax' => '',
  ),
);

