<?php
$jieqiBlocks['1'] = array (
  'bid' => 0,
  'blockname' => '我的书架',
  'module' => 'article',
  'filename' => 'block_ubookcase',
  'classname' => 'BlockArticleUbookcase',
  'side' => -1,
  'title' => '我的书架',
  'vars' => 'lastupdate,2,0,self',
  'template' => 'block_user_ubookcase.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['2'] = array (
  'bid' => 0,
  'blockname' => '日推荐榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '推荐榜',
  'vars' => 'dayvote,4,0,0,0,0',
  'template' => 'block_user_commend.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['3'] = array (
  'bid' => 0,
  'blockname' => '月推荐榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '推荐榜',
  'vars' => 'monthvote,4,0,0,0,0',
  'template' => 'block_user_commend.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['4'] = array (
  'bid' => 0,
  'blockname' => '总推荐榜',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '推荐榜',
  'vars' => 'allvote,4,0,0,0,0',
  'template' => 'block_user_commend.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);
$jieqiBlocks['5'] = array (
  'bid' => 0,
  'blockname' => '猜你喜欢的',
  'module' => 'article',
  'filename' => 'block_articlelist',
  'classname' => 'BlockArticleArticlelist',
  'side' => -1,
  'title' => '猜你喜欢的',
  'vars' => 'toptime,6,0,0,0,0',
  'template' => 'block_user_like.html',
  'contenttype' => 4,
  'custom' => 0,
  'publish' => 3,
  'hasvars' => 1,
  'showtype' => 0,
);

?>
