<?php
$jieqiAction['article'] = array (
  'articleadd' => 
  array (
    'acttitle' => '发表新作',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 0,
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 20,
    'earncredit' => 0,
  ),
  'chapteradd' => 
  array (
    'acttitle' => '增加章节',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 0,
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 10,
    'earncredit' => 0,
  ),
  'reviewadd' => 
  array (
    'acttitle' => '发表书评',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 0,
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 1,
    'earncredit' => 0,
  ),
  'reviewgood' => 
  array (
    'acttitle' => '书评精华',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 0,
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 3,
    'earncredit' => 0,
  ),
  'replyadd' => 
  array (
    'acttitle' => '发表回复',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 0,
    'paytitle' => '',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 1,
    'earncredit' => 0,
  ),
  'rate' => 
  array (
    'acttitle' => '小说评分',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 1,
    'paytitle' => '评分票',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 1,
    'earncredit' => 0,
  ),
  'poll' => 
  array (
    'acttitle' => '小说推荐',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 1,
    'paytitle' => '推荐票',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 1,
    'earncredit' => 0,
  ),
  'down' => 
  array (
    'acttitle' => '小说下载',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 1,
    'paytitle' => '积分',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 0,
    'earncredit' => 0,
  ),
  'flower' => 
  array (
    'acttitle' => '投鲜花',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 1,
    'paytitle' => '鲜花',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 1,
    'earncredit' => 0,
  ),
  'egg' => 
  array (
    'acttitle' => '扔鸡蛋',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 0,
    'ispay' => 1,
    'paytitle' => '鸡蛋',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 1,
    'earncredit' => 0,
  ),
  'vipvote' => 
  array (
    'acttitle' => '投月票',
    'minscore' => '0',
    'islog' => '1',
    'isreview' => '1',
    'isvip' => '1',
    'ispay' => '1',
    'paytitle' => '月票',
    'paybase' => '1',
    'paymin' => '0',
    'paymax' => '0',
    'earnscore' => '3',
    'earncredit' => '1',
    'lenmin' => NULL,
    'lenmax' => NULL,
  ),
  'tip' => 
  array (
    'acttitle' => '打赏小说',
    'minscore' => 0,
    'islog' => 1,
    'isreview' => 1,
    'isvip' => 1,
    'ispay' => 1,
    'paytitle' => '小说币',
    'paybase' => 1,
    'paymin' => 20,
    'paymax' => 0,
    'earnscore' => 1,
    'earncredit' => 2,
    'ismessage' => 0,
  ),
  'buychapter' => 
  array (
    'acttitle' => '订阅章节',
    'minscore' => 0,
    'islog' => 0,
    'isreview' => 0,
    'isvip' => 1,
    'ispay' => 1,
    'paytitle' => '小说币',
    'paybase' => 1,
    'paymin' => 0,
    'paymax' => 0,
    'earnscore' => 2,
    'earncredit' => 1,
  ),
);

